<?php

namespace AppBundle\Repository;

/**
 * TwitterUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TwitterUserRepository extends \Doctrine\ORM\EntityRepository
{
}
